### ISSUE TITLE
docker Error: connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by kimgysen** [mysqljs/mysql#1869]
I have tried for a day to connect to mysql using nodejs and docker, but haven't even succeeded to make a simple database connection.

My docker-compose file looks as follows:

```
version: "2"
services:
  users-api:
    env_file: .env
    build:
      dockerfile: Dockerfile.localdev
      context: ./
      args: 
        - PORT_USERS_API=${PORT_USERS_API}
        - PORT_USERS_DEBUG=${PORT_USERS_DEBUG}
        - PORT_MYSQL=${PORT_MYSQL}
    volumes:
      - ".:/app"
    links:
      - mysql:mysql
    ports:
      - "${PORT_USERS_API}:${PORT_USERS_API}"
      - "${PORT_USERS_DEBUG}:${PORT_USERS_DEBUG}"
  mysql:
    image: mysql
    container_name: mysql-livefeed
    environment:
      - MYSQL_DATABASES=abc_db
      - MYSQL_ROOT_PASSWORD=abc
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=abc
    ports:
      - "${PORT_MYSQL}:${PORT_MYSQL}"
    volumes:
      - ./volumes/mysql:/usr/local/mysql
      - ./src/data/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: on-failure
```
When spinning up the containers, I can log in into the container perfectly fine, and I can also make manual connection to the mysql service with the same credentials just fine.

I've tried both ways for creating a connection:

```
var connection = mysql.createConnection('mysql://root:abc@localhost:3306/livefeed_db?debug=true');

var connection = mysql.createConnection({
    socketPath : '/var/run/mysqld/mysqld.sock',
    user       : 'root',
    password   : 'abc'
});
```
I also checked the location of the mysqld.sock file, which exists.

The result, sadly, is always the same:

> { Error: connect ECONNREFUSED 127.0.0.1:3306
> users-api_1  |     at Object._errnoException (util.js:1031:13)
> users-api_1  |     at _exceptionWithHostPort (util.js:1052:20)
> users-api_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
> users-api_1  |     --------------------
> users-api_1  |     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:145:48)
> users-api_1  |     at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:52:23)
> users-api_1  |     at Connection.connect (/app/node_modules/mysql/lib/Connection.js:130:18)
> users-api_1  |     at Connection._implyConnect (/app/node_modules/mysql/lib/Connection.js:461:10)
> users-api_1  |     at Connection.query (/app/node_modules/mysql/lib/Connection.js:206:8)
> users-api_1  |     at Promise (/app/src/services/User.js:32:18)
> users-api_1  |     at new Promise (<anonymous>)
> users-api_1  |     at Object.exports.findById.id [as findById] (/app/src/services/User.js:23:10)
> users-api_1  |     at Object.exports.test (/app/src/services/Account.js:25:34)
> users-api_1  |     at Server.test (/app/src/web/Account.js:19:47)

After a day of searching, I'm out of options on how to make the connection... 
All hints are welcome, thanks!
